### ISSUE TITLE
repo empty

### ISSUE THREAD

**Issue by rofl0r** [directfb2/LiTE#1]
hi, i've seen your fosdem 2020/2022 talks, and i found LiTE particularly interesting, but haven't been able to find its sources. only reference i found is https://t2sde.org/packages/dfb-lite.html which links to the defunct directfb site. it may be possible to get the linked tarball from web.archive.org in case you don't have the sources either.

**Comment by caramelli** [comment]
The last official version of LiTE was 0.8.10 (released in 2008). So if you search for the LiTE-0.8.10.tar.gz tarball, you should be able to find the source code. But it's quite old and not directly usable...
I still need time before sharing the work I started on this old version of LiTE (that's why the repository is still empty) but I really want to revive this project.

**Comment by caramelli** [comment]
LiTE code has been restored, examples are available at https://github.com/directfb2/LiTE-examples
